// Generated by .codex/skills/wiki-sync/scripts/sync_wiki.py
import { defineConfig } from "vitepress";

const activeItems = [];

const archivedItems = [
  {
    text: "build-plugin-research-mvp",
    link: "/changes/archive/2026-08-27-build-plugin-research-mvp/",
  },
];

export default defineConfig({
  lang: "zh-CN",
  title: "Cangshu Pavilion WIKI",
  description: "Cangshu Pavilion WIKI 文档与 OpenSpec 变更记录",
  cleanUrls: true,
  srcExclude: ["openspec/**"],
  themeConfig: {
    nav: [
      { text: "首页", link: "/" },
      { text: "变更 WIKI", link: "/changes/" },
    ],
    sidebar: {
      "/changes/": [
        { text: "总览", items: [{ text: "变更索引", link: "/changes/" }] },
        { text: "进行中", collapsed: false, items: activeItems },
        { text: "已归档", collapsed: true, items: archivedItems },
      ],
    },
    search: {
      provider: "local",
      options: {
        _render(src, env, md) {
          if (env.relativePath.startsWith("openspec/")) return "";
          const html = md.render(src, env);
          return env.frontmatter?.search === false ? "" : html;
        },
      },
    },
    outline: { level: [2, 3], label: "本页目录" },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "目录",
    returnToTopLabel: "返回顶部",
  },
});
